/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

	public String getHello() {
		return "Hello World. I'm Haseeb";
	}
}
